# Generated by Django 4.0.3 on 2022-05-09 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_book_id_alter_genre_id_alter_staff_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='myapi.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='myapi.staff')),
            ],
        ),
    ]
