version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/backend"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/mobile"
    schedule:
      interval: "daily"