name: cloud_messaging_service
description: Flutter project with useful functions from firebase cloud messaging.
version: 1.1.0-dev.2
publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  # analyzer
  # dart_code_metrics: ^4.17.0
  
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  
  flutter:
    sdk: flutter

  flutter_local_notifications: ^13.0.0
  

  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0