name: cloud_messaging_service
description: Flutter project with useful functions from firebase cloud messaging.
version: 1.1.0-dev.2
publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  # analyzer
  # dart_code_metrics: ^4.17.0
  
  firebase_core: ^1.20.0
  firebase_messaging: ^12.0.1
  
  flutter:
    sdk: flutter

  flutter_local_notifications: ^9.7.0
  

  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1