# Generated by Django 3.0.5 on 2022-05-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='username', max_length=200)),
                ('password', models.CharField(help_text='password', max_length=200)),
                ('last_name', models.CharField(help_text='International identification number assigned to the right owner.', max_length=200, null=True)),
                ('first_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
