# Generated by Django 3.0.5 on 2022-06-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_id',
            field=models.CharField(help_text='International identification number assigned to the right owner.', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(help_text='International identification number assigned to the right owner.', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='International identification number assigned to the right owner.', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='International identification number assigned to the right owner.', max_length=200),
        ),
    ]
