name: authentication_repository
description: A Authentication Repository
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  authentication_data_source:
    path: ../authentication_data_source
  secure_storage_helper:
    path: ../secure_storage_helper

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.22.2
  very_good_analysis: ^3.1.0
