# Generated by Django 3.0.5 on 2022-06-18 08:14

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=26)),
                ('receiver', models.CharField(max_length=26, null=True)),
            ],
        ),
    ]
