name: models
description: A package contains all models in app
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.4.0
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  test: ^1.22.2
  very_good_analysis: ^3.1.0
