# Generated by Django 3.0.5 on 2022-06-18 12:57

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('following_count', models.IntegerField(default=0)),
                ('follower_count', models.IntegerField(default=0)),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=1000)),
                ('num_blog', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
