name: blog_data_source
description: A blog data source package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  http_client_handler:
    path: "../http_client_handler"
  json_annotation: ^4.7.0
  models:
    path: "../models"

dev_dependencies:
  build_runner: ^2.4.0
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  test: ^1.22.2
  very_good_analysis: ^3.1.0
